### ISSUE TITLE
Исправить ошибку с голосованием за удаленный пост

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/mayakovskiy#3]
Если пользователь удаляет пост, который находился в плане по голосованию, сервис падает. 
Необходимо добавить обработку данной ошибки 
![image.png](https://images.zenhubusercontent.com/5a27458f8a75884b908a072e/d7a0738d-9696-45b8-a8de-5cdef342b6ad)

2018-09-10 09:56:45 <1> [error] Like Machine request error - Error: invalid operation in transaction (3010000)
Invalid operation 0 in transaction: Missing object (1020200)
Missing comment with id "{"account":"ACCOUNT NAME","permlink":"PERMLINK"}"

**Comment by zavz9t** [comment]
Добрый день. Я верно понимаю, что из-за этого бага, сейчас не работает поддержка постов написанных через голос.ио?

**Comment by NickShtefan** [comment]
да, в данный момент работа бота восстановлена, баг будет устранен в ближайшее время
