### ISSUE TITLE
Изменить логику подбора постов для апа от golos.io

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/mayakovskiy#4]
Внедрить проверку на наличие тега (добавить в настройки)
Внедрить проверку на приложение 
Перенести проверку на выставленного бенефициара в настройки

**Comment by NickShtefan** [comment]
Добавить проверку на отсутсвие parent_permlink

**Comment by zavz9t** [comment]
Заранее извиняюсь, если не в тему.

> Добавить проверку на отсутсвие parent_permlink

Если цель фильтрация на комментарии, то нужно проверять `parent_author`, который пустой для поста, но содержит информацию в случае комментария. А в поле `parent_permlink` для поста прописывается первый тег поста (название категории).

**Comment by Format-X22** [comment]
parent_permlink это ошибка, конечно же parent_author.
И он проверяется, однако так как один из пользователей выразил сомнения - было перепроверено. И оно действительно как проверялось - так и проверяется сейчас.
По сути Тикет более не актуален - всё реализовано и уже работает.
Закрываю.
